name: Test and release
on:
    push:


jobs:
    release-docker:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Log in to GitHub container registry
              uses: docker/login-action@v3.3.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ github.token }}

            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            - name: Build container image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: |
                  ghcr.io/${{ env.REPO }}/wordpress-hardened:${{ github.sha }}
                  ghcr.io/${{ env.REPO }}/wordpress-hardened:latest
                  cache-from: ghcr.io/${{ env.REPO }}/wordpress-hardened:latest
